apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "private-gpt.fullname" . }}
  labels:
    {{- include "private-gpt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "private-gpt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "private-gpt.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8001
          env:
            - name: PORT
              value: "8001"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
